services:
  tabby:
    restart: no
    image: registry.tabbyml.com/tabbyml/tabby
    command: serve --model colefuerth/DeepseekCoder-6.7B-instruct-Q5_K_S --device cuda
    volumes:
      - "$HOME/.tabby:/data"
      - /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:ro
      - /usr/lib/nvidia:/usr/lib/nvidia:ro
    ports:
      - 8080:8080
    privileged: true
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/nvidia