#!/usr/bin/zsh

# load and unload the ramdisk from a tarball

RD_IMG='./ramdisk.tar'
RD_MP='./ramdisk'
RD_SIZE='40G'

# Parameters can ve changed per-session, with:
# RD_MP="$PWD/buildcore" && RD_IMG="$RD_MP".tar && RD_SIZE='30G'

delete_rd() {
    rm "$RD_IMG"
}

mount_rd() {
    echo "Mounting $RD_SIZE ramdisk at $RD_MP!"
    sudo mkdir -p "$RD_MP"
    sudo mount -o size=$RD_SIZE -t tmpfs none "$RD_MP"
    sudo chmod 1777 "$RD_MP"  # Set permissions, including the sticky bit
    sudo chown "$USER:$USER" "$RD_MP"  # Set ownership to the current user
}

unmount_rd() {
    echo "Unmounting $RD_SIZE ramdisk at $RD_MP!"
    sudo umount "$RD_MP"
    sudo rm -rf "$RD_MP"
}

restore_rd() {
    if [[ ! -f "$RD_IMG"  || ! -d "$RD_MP" ]]; then
        echo "Ramdisk img does not exist, or ramdisk is not mounted!"
        return 1
    fi
    pv "$RD_IMG" | tar -x -C "$RD_MP" -f -
}

backup_rd() {
    tar -cf - -C "$RD_MP" . | pv -s "$(du -sb $RD_MP | awk '{print $1}')" > "$RD_IMG"
}
