#!/usr/bin/env bash

# for those wondering: your old bashrc file is under "~/.bash_aliases/.bashrc"

export SHRC="bash"

# Load bash alias files from ~/bash_aliases/
for file in $HOME/.bash_aliases/*; do
    source "$file"
done

# load completion functions for custom scripts, if installed
if [ -d ~/.bash_completion.d ]; then
    for f in ~/.bash_completion.d/*; do source $f; done
fi

# syntax highlighting
[ -f ~/.local/share/blesh/ble.sh ] && source ~/.local/share/blesh/ble.sh

# autocomplete
[ -f ~/.repos/linecomp/linecomp.sh ] && source ~/.repos/linecomp/linecomp.sh
