#!/usr/bin/bash

# for those wondering: your old bashrc file is under "~/.bash_aliases/.bashrc"

SCRIPTS_DIR="$HOME/dot-files"
if [ ! -z SCRIPTS_DIR ] && [ -r "$SCRIPTS_DIR/config.bash" ] && grep -q "AUTO_UPDATE=true" "$SCRIPTS_DIR/config.bash"; then
    (cd $SCRIPTS_DIR && ./update.sh)
fi

export SHRC="bash"

# Load bash alias files from ~/bash_aliases/
for file in $HOME/.bash_aliases/*; do
    source "$file"
done

# load completion functions for custom scripts, if installed
if [ -d ~/.bash_completion.d ]; then
    for f in ~/.bash_completion.d/*; do source $f; done
fi
