#!/usr/bin/env zsh

# for those wondering: your old zshrc file is under "~/.zsh_aliases/.zshrc"

export DISABLE_UPDATE_PROMPT=true
export SHRC="zsh"

ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""

# Add nix completions to fpath before oh-my-zsh initializes
if command -v nix &> /dev/null; then
  NIX_PATH=$(dirname $(dirname $(which nix)))
  if [[ -d "$NIX_PATH/share/zsh/site-functions" ]]; then
    fpath=($NIX_PATH/share/zsh/site-functions $fpath)
  fi
fi

plugins=(git zsh-autosuggestions zsh-syntax-highlighting) #syntax must be last
source $ZSH/oh-my-zsh.sh

# Load zsh-autocomplete AFTER oh-my-zsh (prevents it from overriding arrow keys)
if [[ -f ~/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh ]]; then
  source ~/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
fi

# load completion functions for custom scripts, if installed
if [ -d ~/.bash_completion.d ]; then
    for f in ~/.bash_completion.d/*; do source $f; done
fi

# Load Zsh alias files from ~/zsh_aliases/
for file in $HOME/.zsh_aliases/*; do
    source "$file"
done

unsetopt share_history
setopt inc_append_history
