format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$status\
$line_break\
$conda\
$character"""

command_timeout = 1000  # 1 second

[hostname]
ssh_symbol = ""

[directory]
read_only = " ro"
style = "blue"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[status]
style = "red"
symbol = "↵ "
disabled = false

[character]
success_symbol = "[>](bold purple)"
error_symbol = "[>](bold red)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
symbol = "git "

[python]
symbol = "py "
# pyenv_version_name = false

# Display the version of python from inside a local venv.
#
# Note this will only work when the venv is inside the project and it will only
# work in the directory that contains the venv dir but maybe this is ok?
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
