#!/usr/bin/env bash

set -euo pipefail

# Use nix-output-monitor is available else fall back to nix
NIX=$(if [ ! -z $(which nom) ]; then echo "nom"; else echo "nix"; fi)

REMOTE="eu.nixbuild.net"

RESULT_PATH=$(
    $NIX build \
        --print-out-paths \
        --system aarch64-linux \
        --max-jobs 0 \
        --eval-store auto \
        --store ssh-ng://$REMOTE \
        --log-format internal-json -v \
        $*
)
# if `nix-store --verify-path $RESULT_PATH` fails, then we need to copy the result to the local store, make sure to mute stderr
if ! $NIX store --verify-path $RESULT_PATH 2>/dev/null; then
    nix copy --from "ssh-ng://$REMOTE" $RESULT_PATH
    # nix-copy-closure --from "ssh://$REMOTE" --include-outputs --gzip --use-substitutes $RESULT_PATH
fi
echo $RESULT_PATH
