#!/usr/bin/env bash

set -euo pipefail

# Use nix-output-monitor if available, else fall back to nix
command -v nom >/dev/null && NIX=nom || NIX=nix

REMOTE="${REMOTE:-s}"
SYSTEM="${SYSTEM:-aarch64-linux}"

RESULT_PATH=$(
    $NIX build -L \
        --print-out-paths \
        --system "$SYSTEM" \
        --max-jobs 0 \
        --eval-store auto \
        --store ssh-ng://$REMOTE \
        --verbose \
        $*
)
# if `nix-store --verify-path $RESULT_PATH` fails, then we need to copy the result to the local store, make sure to mute stderr
if ! nix-store --verify-path $RESULT_PATH 2>/dev/null; then
    nix-copy-closure --gzip --from "$REMOTE" $RESULT_PATH
fi
echo $RESULT_PATH
