# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."luks-581acec0-3833-4157-9d4d-0e806a4c0476".device =
    "/dev/disk/by-uuid/581acec0-3833-4157-9d4d-0e806a4c0476";

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/a53a469a-096e-411d-b19a-485f966785b8";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/6BE1-B655";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
    "/data" = {
      device = "/dev/disk/by-uuid/2da192ba-6428-4ee7-a06b-737279d3ca60";
      fsType = "ext4";
    };
  };

  boot.initrd.luks.devices."luks-3923f187-539e-4ff4-b600-10c198fae8fe".device =
    "/dev/disk/by-uuid/3923f187-539e-4ff4-b600-10c198fae8fe";

  swapDevices = [ { device = "/dev/disk/by-uuid/5a024444-2f23-4a5d-82ea-f624083083a4"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp72s0u2u4u4u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
